"""
Email service — sends the AI-generated summary to the recipient via SMTP.
Uses aiosmtplib for async sending so it doesn't block FastAPI event loop.
"""
import os
from email.mime.multipart import MIMEMultipart
from email.mime.text import MIMEText

import aiosmtplib
from dotenv import load_dotenv

load_dotenv()


async def send_summary_email(recipient: str, summary: str) -> None:
    smtp_host = os.environ["SMTP_HOST"]
    smtp_port = int(os.getenv("SMTP_PORT", 587))
    smtp_user = os.environ["SMTP_USER"]
    smtp_password = os.environ["SMTP_PASSWORD"]
    email_from = os.getenv("EMAIL_FROM", smtp_user)

    # Build a nicely formatted HTML email
    html_body = f"""
    <html>
      <body style="font-family: Arial, sans-serif; line-height: 1.6; color: #333;">
        <h2 style="color: #2563EB;">📊 Sales Insight Summary</h2>
        <p>Your AI-generated sales summary is ready:</p>
        <hr/>
        <div style="background:#f4f4f4; padding:16px; border-radius:8px; white-space:pre-wrap;">
{summary}
        </div>
        <hr/>
        <small>This email was generated by Sales Insight Automator.</small>
      </body>
    </html>
    """

    msg = MIMEMultipart("alternative")
    msg["Subject"] = "📊 Your Sales Insight Summary"
    msg["From"] = email_from
    msg["To"] = recipient
    msg.attach(MIMEText(summary, "plain"))
    msg.attach(MIMEText(html_body, "html"))

    await aiosmtplib.send(
        msg,
        hostname=smtp_host,
        port=smtp_port,
        username=smtp_user,
        password=smtp_password,
        start_tls=True,
    )
