"""
email_service.py
────────────────
Sends the AI-generated summary to the recipient using async SMTP
(aiosmtplib) so the FastAPI event loop is never blocked.

Configuration (via .env):
    SMTP_HOST      — e.g. smtp.gmail.com
    SMTP_PORT      — default 587  (STARTTLS)
    SMTP_USER      — your Gmail / SMTP account
    SMTP_PASSWORD  — Gmail App Password (not your login password)
    EMAIL_FROM     — display address (defaults to SMTP_USER)
"""
import os
from email.mime.multipart import MIMEMultipart
from email.mime.text import MIMEText

import aiosmtplib
from dotenv import load_dotenv

load_dotenv()

# ── Configuration ──────────────────────────────────────────────────────────────
_SMTP_HOST: str = os.getenv("SMTP_HOST", "smtp.gmail.com")
_SMTP_PORT: int = int(os.getenv("SMTP_PORT", "587"))
_SMTP_USER: str = os.getenv("SMTP_USER", "")
_SMTP_PASSWORD: str = os.getenv("SMTP_PASSWORD", "")
_EMAIL_FROM: str = os.getenv("EMAIL_FROM", _SMTP_USER)


# ── Public API ─────────────────────────────────────────────────────────────────

async def send_summary_email(recipient: str, summary: str, rows_analyzed: int) -> None:
    """
    Send the AI-generated executive summary to *recipient* via SMTP.

    Args:
        recipient:     Destination email address (already validated by FastAPI).
        summary:       Plain-text summary produced by the AI service.
        rows_analyzed: Number of data rows, shown in the email footer.

    Raises:
        EnvironmentError: if SMTP credentials are not configured.
        aiosmtplib.SMTPException: on any SMTP-level failure.
    """
    _validate_smtp_config()

    message = _build_email(recipient=recipient, summary=summary, rows_analyzed=rows_analyzed)

    await aiosmtplib.send(
        message,
        hostname=_SMTP_HOST,
        port=_SMTP_PORT,
        username=_SMTP_USER,
        password=_SMTP_PASSWORD,
        start_tls=True,         # upgrades the connection to TLS (port 587)
    )


# ── Private helpers ────────────────────────────────────────────────────────────

def _validate_smtp_config() -> None:
    missing = [k for k, v in {
        "SMTP_USER": _SMTP_USER,
        "SMTP_PASSWORD": _SMTP_PASSWORD,
        "SMTP_HOST": _SMTP_HOST,
    }.items() if not v]

    if missing:
        raise EnvironmentError(
            f"Missing SMTP configuration: {', '.join(missing)}. "
            "Please fill in the values in your .env file."
        )


def _build_email(recipient: str, summary: str, rows_analyzed: int) -> MIMEMultipart:
    """Assemble a MIMEMultipart email with both plain-text and HTML parts."""
    msg = MIMEMultipart("alternative")
    msg["Subject"] = "📊 Your Sales Insight Summary is Ready"
    msg["From"] = _EMAIL_FROM
    msg["To"] = recipient

    # ── Plain-text fallback ──────────────────────────────────────────────────
    plain = (
        "Sales Insight Automator\n"
        "═══════════════════════\n\n"
        f"{summary}\n\n"
        f"── {rows_analyzed} data rows analyzed ──\n"
        "Generated by Sales Insight Automator"
    )

    # ── HTML version ─────────────────────────────────────────────────────────
    # Convert newlines in summary to <br> tags for the HTML body
    summary_html = summary.replace("\n", "<br>")

    html = f"""<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Sales Insight Summary</title>
</head>
<body style="margin:0;padding:0;background-color:#0f172a;font-family:Arial,Helvetica,sans-serif;">
  <table width="100%" cellpadding="0" cellspacing="0"
         style="background-color:#0f172a;padding:40px 0;">
    <tr>
      <td align="center">
        <table width="600" cellpadding="0" cellspacing="0"
               style="background-color:#1e293b;border-radius:12px;
                      border:1px solid #334155;overflow:hidden;
                      box-shadow:0 4px 24px rgba(0,0,0,0.4);">

          <!-- Header -->
          <tr>
            <td style="background:linear-gradient(135deg,#1d4ed8,#7c3aed);
                       padding:32px 40px;text-align:center;">
              <h1 style="margin:0;color:#ffffff;font-size:24px;font-weight:700;">
                📊 Sales Insight Summary
              </h1>
              <p style="margin:8px 0 0;color:#bfdbfe;font-size:14px;">
                AI-powered executive report
              </p>
            </td>
          </tr>

          <!-- Body -->
          <tr>
            <td style="padding:36px 40px;">
              <div style="background:#0f172a;border:1px solid #334155;
                          border-radius:8px;padding:24px;
                          color:#e2e8f0;font-size:15px;line-height:1.8;">
                {summary_html}
              </div>
            </td>
          </tr>

          <!-- Footer -->
          <tr>
            <td style="padding:0 40px 32px;text-align:center;">
              <p style="margin:0;color:#64748b;font-size:12px;">
                {rows_analyzed} data rows analyzed &nbsp;·&nbsp;
                Generated by <strong style="color:#94a3b8;">
                  Sales Insight Automator
                </strong>
              </p>
            </td>
          </tr>

        </table>
      </td>
    </tr>
  </table>
</body>
</html>"""

    msg.attach(MIMEText(plain, "plain"))
    msg.attach(MIMEText(html, "html"))
    return msg
